spring:

  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true

  # Spring JPA
  h2.console.enabled: true
  jpa:
    database: H2
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: sa

elasticsearch:
  user: elastic
  password: '@elasticsearch.password@'
  host: '@elasticsearch.host@'
  port: 9200
  connectTimeout: 10
  socketTimeout: 30

dave:
  email:
    address: <dave mailadress>
    password: <password>
