apiVersion: v2
name: dave-backend-chart
description: DAVe traffic counting plattform, backend
type: application
version: ${project.version}
appVersion: "${project.version}"
maintainers:
  - name: klml
    email: klml@muenchen.de
  - name: Starwit Technologies GmbH
    email: foss@starwit.de
home: https://github.com/starwit/dave-backend/tree/sprint/stack/helm/dave-backend
#icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/starwit/dave-backend/tree/sprint/stack/helm/dave-backend"
  - "https://github.com/starwit/timescaledb-chart/tree/main/postgres"
