-- Löschen der Datensaetze aus den Tabellen
delete from optionsmenuesettings;


insert into optionsmenuesettings(id,
                                 created_time,
                                 version,
                                 fahrzeugklasse,
                                 intervall,
                                 kraftfahrzeugverkehr_choosable_intervals,
                                 schwerverkehr_choosable_intervals,
                                 gueterverkehr_choosable_intervals,
                                 schwerverkehrsanteil_prozent_choosable_intervals,
                                 gueterverkehrsanteil_prozent_choosable_intervals,
                                 radverkehr_choosable_intervals,
                                 fussverkehr_choosable_intervals,
                                 lastkraftwagen_choosable_intervals,
                                 lastzuege_choosable_intervals,
                                 busse_choosable_intervals,
                                 kraftraeder_choosable_intervals,
                                 personenkraftwagen_choosable_intervals,
                                 lieferwagen_choosable_intervals)
values (gen_random_uuid(),
        now(),
        0,
        'SUMME_KFZ',
        'STUNDE_KOMPLETT',
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        now(),
        0,
        'SUMME_KFZ',
        'STUNDE_VIERTEL',
        '[
          "STUNDE_VIERTEL",
          "STUNDE_HALB",
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        now(),
        0,
        'ZWEI_PLUS_EINS',
        'STUNDE_KOMPLETT',
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        now(),
        0,
        'ACHT_PLUS_EINS',
        'STUNDE_KOMPLETT',
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb),
       (gen_random_uuid(),
        now(),
        0,
        'ACHT_PLUS_EINS',
        'STUNDE_VIERTEL_EINGESCHRAENKT',
        '[
          "STUNDE_VIERTEL",
          "STUNDE_HALB",
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb),
       (gen_random_uuid(),
        now(),
        0,
        'RAD',
        'STUNDE_KOMPLETT',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        now(),
        0,
        'RAD',
        'STUNDE_VIERTEL',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '[
          "STUNDE_VIERTEL",
          "STUNDE_HALB",
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        now(),
        0,
        NULL,
        NULL,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        '[
          "STUNDE_KOMPLETT"
        ]'::jsonb,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL)
;

