name: build2

on:
  push:
    branches:
      - demotest
  pull_request:
    branches:
      - demotest

jobs:
  build2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: build2
        id: maven
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "workflow_dispatch"
          else
            echo "push?"
          fi
