name: build maven and image

on:
#  pull_request:
#    branches:
#      - demotest # TODO: demo
  push:
    branches:
      - demotest
#  workflow_dispatch:
#    inputs:
#      tag:
#        description: 'What should the image be tagged as?'
#        required: false
#        default: 'demotest' # TODO: demo

env:
  IMAGE_NAME: "dave-backend"
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  buildAndTag:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: build and tag
        id: build-and-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "workflow_dispatch"
          else
            echo "push?"
          fi
