name: test-FV-327

on:
  repository_dispatch:
    types: [trigger_release_action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Empfangene Parameter anzeigen
        env:
          RELEASE_VERSION: ${{ github.event.client_payload.releaseVersion }}
          DEVELOPMENT_VERSION: ${{ github.event.client_payload.developmentVersion }}
        run: |
          echo "releaseVersion: $RELEASE_VERSION"
          echo "developmentVersion: $DEVELOPMENT_VERSION"