name: test-FV-327

on:
  repository_dispatch:
    types: [trigger_release_action]
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version number to be released (e.g., 1.2.3)"
        required: true
        default: "6.0.0"
      developmentVersion:
        description: "Next version number with snapshot (e.g., 1.2.4-SNAPSHOT)"
        required: true
        default: "6.0.1-SNAPSHOT"
      use-pr:
        description: "Use PR for version bump instead of direct push"
        default: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Empfangene Parameter anzeigen
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            RELEASE_VERSION="${{ github.event.client_payload.releaseVersion }}"
            DEVELOPMENT_VERSION="${{ github.event.client_payload.developmentVersion }}"
            SRC="event"
          else
            RELEASE_VERSION="${{ github.inputs.releaseVersion }}"
            DEVELOPMENT_VERSION="${{ github.inputs.developmentVersion }}"
            SRC="manuell"
          fi
          echo "releaseVersion: $RELEASE_VERSION"
          echo "developmentVersion: $DEVELOPMENT_VERSION"
          echo "src: $SRC"